### ISSUE TITLE
Hope to provide a demo of video real-time inference

### ISSUE THREAD

**Issue by Deep-learning999** [AIFARMS/NOR-behavior-recognition#1]
Hope to provide a demo of video real-time inference

**Comment by Deep-learning999** [comment]
I also want to know which columns are mainly used to identify pig behavior

**Comment by ani8897** [comment]
You can follow the instruction here to run the code on your machine: https://github.com/AIFARMS/NOR-behavior-recognition/blob/master/README.md#demo

We are currently using the TSM network to predict pig behavior. Specifically, the [extract_frames.py](data/extract_frames.py) script in the ``data`` folder uses [action_annotations.csv](https://drive.google.com/file/d/1IaP95Oqf2NDdhn1YA6RNhgZmpqrrXOzL/view?usp=sharing) to extract the relevant action frames for training.
