### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by z929407579** [AIFARMS/NOR-behavior-recognition#2]
When  i  run extract_frames.py  ,I met a problem, as follows:
D:\anaconda\envs\nor\python.exe E:/NOR/data/extract_frames.py
1815_C1_548_4wk
Traceback (most recent call last):
  File "E:/NOR/data/extract_frames.py", line 45, in <module>
    assert actions_df.iloc[0]['Behaviour'] == 'Begin Trial'
AssertionError

Can you help  me  solve the problem?   Thanh you  so much.

**Comment by zhouhaojndx** [comment]
I have the same problem and I don't know how to fix it.
